"""Pydantic response models for Finnhub API responses."""

from mcp_finnhub.api.models.common import (
    CandleResponse,
    CompanyProfile,
    MarketStatusResponse,
    NewsArticle,
    QuoteResponse,
    Resolution,
    SymbolLookupResult,
)
from mcp_finnhub.api.models.estimates import (
    EarningsEstimateInfo,
    EarningsEstimates,
    EbitdaEstimateInfo,
    EbitdaEstimates,
    PriceTarget,
    RecommendationTrend,
    RevenueEstimateInfo,
    RevenueEstimates,
)
from mcp_finnhub.api.models.fundamentals import (
    BasicFinancials,
    BasicFinancialsResponse,
    DividendData,
    ReportedFinancial,
    ReportedFinancialsResponse,
    RevenueBreakdownData,
    RevenueBreakdownResponse,
    RevenueGeography,
    RevenueProduct,
    SecFinancialData,
    SecFinancialsResponse,
    SplitData,
)
from mcp_finnhub.api.models.market import (
    EarningsData,
    EarningsResponse,
    FinancialMetric,
    FinancialReport,
    FinancialsResponse,
    SymbolSearchResponse,
)
from mcp_finnhub.api.models.news import (
    InsiderSentimentResponse,
    InsiderTransaction,
    NewsSentimentResponse,
    SentimentBuzz,
    SentimentScore,
)
from mcp_finnhub.api.models.ownership import (
    CongressionalTrade,
    CongressionalTrading,
    InsiderTransactionData,
    InsiderTransactions,
    InstitutionalOwnership,
    InstitutionalOwnershipData,
    InstitutionalOwnershipPosition,
    InstitutionalPortfolio,
    PortfolioData,
    PortfolioHolding,
)
from mcp_finnhub.api.models.technical import (
    AggregateSignalsResponse,
    IndicatorResponse,
    IndicatorValue,
    Pattern,
    PatternRecognitionResponse,
    SignalCount,
    SupportResistanceLevel,
    SupportResistanceResponse,
    TechnicalAnalysis,
    TrendInfo,
)

__all__ = [
    # Technical analysis models
    "AggregateSignalsResponse",
    # Fundamentals models
    "BasicFinancials",
    "BasicFinancialsResponse",
    # Common models
    "CandleResponse",
    "CompanyProfile",
    # Ownership models
    "CongressionalTrade",
    "CongressionalTrading",
    "DividendData",
    # Market data models
    "EarningsData",
    # Estimates models
    "EarningsEstimateInfo",
    "EarningsEstimates",
    "EarningsResponse",
    "EbitdaEstimateInfo",
    "EbitdaEstimates",
    "FinancialMetric",
    "FinancialReport",
    "FinancialsResponse",
    "IndicatorResponse",
    "IndicatorValue",
    # News and sentiment models
    "InsiderSentimentResponse",
    "InsiderTransaction",
    "InsiderTransactionData",
    "InsiderTransactions",
    "InstitutionalOwnership",
    "InstitutionalOwnershipData",
    "InstitutionalOwnershipPosition",
    "InstitutionalPortfolio",
    "MarketStatusResponse",
    "NewsArticle",
    "NewsSentimentResponse",
    "Pattern",
    "PatternRecognitionResponse",
    "PortfolioData",
    "PortfolioHolding",
    "PriceTarget",
    "QuoteResponse",
    "RecommendationTrend",
    "ReportedFinancial",
    "ReportedFinancialsResponse",
    "Resolution",
    "RevenueBreakdownData",
    "RevenueBreakdownResponse",
    "RevenueEstimateInfo",
    "RevenueEstimates",
    "RevenueGeography",
    "RevenueProduct",
    "SecFinancialData",
    "SecFinancialsResponse",
    "SentimentBuzz",
    "SentimentScore",
    "SignalCount",
    "SplitData",
    "SupportResistanceLevel",
    "SupportResistanceResponse",
    "SymbolLookupResult",
    "SymbolSearchResponse",
    "TechnicalAnalysis",
    "TrendInfo",
]
